### ISSUE TITLE
Installing from pip fails

### ISSUE THREAD

**Issue by gibbbone** [lamyj/wsl-path-converter#1]
Hi,
when I try to install using `pip` it fails with message:
```bash
Could not find a version that satisfies the requirement wsl-path-converter (from versions: )
No matching distribution found for wsl-path-converter
```
Also I cannot find the package on pypy (and the URL in the readme just redirect to pypy homepage).

I don't know how to solve this but a quick fix would be to remove at all the pypy references in the readme and just ask the user to clone the repo and install.

**Comment by lamyj** [comment]
Sorry about that, I forgot to upload to PyPi. It's now fixed: https://pypi.org/project/wsl-path-converter/ (caution: the rendering of the README on the PyPi page is broken).
